# data_path = 'Recommendation/data/'
data_path: "/Users/rahil/Documents/Online_Retail_Recommendation_Project/data/"
search_rows_limit: 10000  # Number of rows to be processed for search
search_cust_limit: 100