# data_path = 'Recommendation/data/'
data_path: "/Users/rahil/Documents/Online_Retail_Recommendation_Project/data/"
search_rows_limit: 100000  # Number of rows to be considered for recomendation, higher the number more the computation time
search_cust_limit: 1000 # Number of customers to be considered for recomendation, higher the number more the computation time